plugins {
    id 'java'
}

group = 'com.architect.path'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

dependencies {
    // 1. The Engine: Playwright (Java Binding)
    implementation 'com.microsoft.playwright:playwright:1.49.0'

    // 2. The Runner: TestNG (Industry Standard for Java)
    testImplementation 'org.testng:testng:7.9.0'

    // 3. The Visualizer: Allure (For Dashboards later)
    testImplementation 'io.qameta.allure:allure-testng:2.25.0'
}

test {
    useTestNG() // Tells Gradle to use TestNG, not JUnit
}